### ISSUE TITLE
how do I create connectionString

### ISSUE THREAD

**Issue by arfan** [mevdschee/go-crud-api#17]
Dear,
I want to try this and I get error like this:

`2017/11/27 17:11:40 dial localhost: unknown network localhost`

im using phpmyadmin on mac, so the host will be `localhost` and username is root with no passowrd

here is the connection string:

`connectionString = "root:@localhost(/var/run/mysqld/mysqld.sock)/php-crud-api" `

Regards

**Comment by mevdschee** [comment]
Maybe:

    root:@127.0.0.1:3306/php-crud-api

But I'm not sure.

**Comment by arfan** [comment]
I have found it like this `root:@tcp(localhost:3306)/dbname` can work
